services:
  - type: web
    name: todoapp
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn todo.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
